---
title: "IGT_Modeling"
author: "Eliany Perez"
date: "3/10/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
pvl: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd ("C:/Users/elianyperez/Desktop/Rmodeling")


#to change settings for r to run go to https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started
library(devtools)
library(hBayesDM)
library(rstan)
library(ggplot2)
library(ggpubr)
library(ggcorrplot)
```

Run PVL model

```{r pvl model}
#pvl<-igt_pvl_delta(data = "C:/Users/elianyperez/Desktop/Rmodeling/igt_data2.txt", niter = 4000, nwarmup = 1000,
 #             nchain = 4, ncore = 1, nthin = 1, inits = "vb",
  #            indPars = "mean", modelRegressor = FALSE, vb = FALSE,
   #           inc_postpred = FALSE, adapt_delta = 0.95, stepsize = 1,
    #          max_treedepth = 10)

```

```{r}
# Visually check convergence of the sampling chains (should look like 'hairy caterpillars')
#plot(pvl, type = "trace")

# Check Rhat values (all Rhat values should be less than or equal to 1.1)
#rhat(pvl)

# Plot the posterior distributions of the hyper-parameters (distributions should be unimodal)
#plot(pvl)

# Show the WAIC and LOOIC model fit estimates
#printFit(pvl)
```

Run orl model

```{r orl model}
#orl<-igt_orl(data = "C:/Users/elianyperez/Desktop/Rmodeling/igt_data2.txt", niter = 4000, nwarmup = 1000, nchain = 4,
 # ncore = 1, nthin = 1, inits = "vb", indPars = "mean",
  #modelRegressor = FALSE, vb = FALSE, inc_postpred = FALSE,
  #adapt_delta = 0.95, stepsize = 1, max_treedepth = 10)
```

```{r}
# Visually check convergence of the sampling chains (should look like 'hairy caterpillars')
#plot(orl, type = "trace")

# Check Rhat values (all Rhat values should be less than or equal to 1.1)
#rhat(orl)

# Plot the posterior distributions of the hyper-parameters (distributions should be unimodal)
#plot(orl)

# Show the WAIC and LOOIC model fit estimates
#printFit(orl)
```

Run vpp model

```{r vpp model}
#vpp<-igt_vpp(data = "C:/Users/elianyperez/Desktop/Rmodeling/igt_data2.txt", niter = 4000, nwarmup = 1000, nchain = 4,
 # ncore = 4, nthin = 1, inits = "vb", indPars = "mean",
  #modelRegressor = FALSE, vb = FALSE, inc_postpred = FALSE,
  #adapt_delta = 0.95, stepsize = 1, max_treedepth = 10)
```

```{r}
# Visually check convergence of the sampling chains (should look like 'hairy caterpillars')
#plot(vpp, type = "trace")

# Check Rhat values (all Rhat values should be less than or equal to 1.1)
#rhat(vpp)

# Plot the posterior distributions of the hyper-parameters (distributions should be unimodal)
#plot(vpp)

# Show the WAIC and LOOIC model fit estimates
#printFit(vpp)

#save.image(vpp.RData)
```

Correlations between mode parameters and raw E choice

```{r}
  #load(vpp.RData)
  setwd("C:/Users/elianyperez/Desktop/Rmodeling")
  pvlPars<-as.data.frame(pvl$allIndPars)
  orlPars<-as.data.frame(orl$allIndPars)
  vppPars<-as.data.frame(vpp$allIndPars)
  Echoice<- read.csv("C:/Users/elianyperez/Desktop/Rmodeling/Etotal.csv")
  
  names(pvlPars)<-c("ID","pvl_A","pvl_alpha","pvl_cons","pvl_lambda")
  names(orlPars)<-c("ID","orl_Arew","orl_Apun","orl_K","orl_betaF","orl_betaP" )
  names(vppPars)<-c("ID","vpp_A","vpp_alpha","vpp_cons","vpp_lambda","vpp_epP","vpp_epN","vpp_K","vpp_w")
  
  #merge- can only merge 2 at a time
  merged<-merge(pvlPars,orlPars,by.x="ID")
  merged2<-merge(vppPars,Echoice,by.x="ID")
  mergedPars<-merge(merged,merged2,by.x="ID")

names(mergedPars)
  
  #choose columns
  mergedPars<- mergedPars[c("pvl_A","pvl_alpha","pvl_cons","pvl_lambda","orl_Arew","orl_Apun","orl_K","orl_betaF","orl_betaP","vpp_A","vpp_alpha","vpp_cons","vpp_lambda","vpp_epP","vpp_epN","vpp_K","vpp_w","E_choice")] 
  
  pvlPars<-mergedPars[c("pvl_A","pvl_alpha","pvl_cons","pvl_lambda","E_choice")] 
  orlPars<-mergedPars[c("orl_Arew","orl_Apun","orl_K","orl_betaF","orl_betaP","E_choice")]
  vppPars<-mergedPars[c("vpp_A","vpp_alpha","vpp_cons","vpp_lambda","vpp_epP","vpp_epN","vpp_K","vpp_w","E_choice")] 
  
  #if you want to write the file
  write.csv(mergedPars, "C:/Users/elianyperez/Desktop/Rmodeling/AllIndpars.csv", row.names=FALSE)

```

```{r}
  theme_set(
    theme_minimal() +
      theme(legend.position = "right")
  )
  a <- ggplot(mergedPars, aes(x = E_choice, y = pvl_A))
  # Scatter plot with regression line
  a + geom_point()+
      geom_smooth(method = "lm") 
  cor.test(mergedPars$E_choice, mergedPars$pvl_A,method = c("pearson", "kendall", "spearman"))
```

```{r}

  b <- ggplot(mergedPars, aes(x = E_choice, y = pvl_alpha))
  # Scatter plot with regression line
  b + geom_point()+
      geom_smooth(method = "lm") 
cor.test(mergedPars$E_choice, mergedPars$pvl_alpha,method = c("pearson", "kendall", "spearman"))
```

```{r}

  c <- ggplot(mergedPars, aes(x = E_choice, y = pvl_cons))
  # Scatter plot with regression line
  c + geom_point()+
      geom_smooth(method = "lm")
cor.test(mergedPars$E_choice, mergedPars$pvl_cons,method = c("pearson", "kendall", "spearman"))
```

```{r}

  d <- ggplot(mergedPars, aes(x = E_choice, y = pvl_lambda))
  # Scatter plot with regression line
  d + geom_point()+
      geom_smooth(method = "lm") 

```

```{r}

  e <- ggplot(mergedPars, aes(x = E_choice, y = orl_Arew))
  # Scatter plot with regression line
  e + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}

  f <- ggplot(mergedPars, aes(x = E_choice, y = orl_Apun))
  # Scatter plot with regression line
  f + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}

  g <- ggplot(mergedPars, aes(x = E_choice, y = orl_K))
  # Scatter plot with regression line
  g + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}

  h <- ggplot(mergedPars, aes(x = E_choice, y = orl_betaF))
  # Scatter plot with regression line
  h + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}

  i <- ggplot(mergedPars, aes(x = E_choice, y = orl_betaP))
  # Scatter plot with regression line
  i + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}
  j <- ggplot(mergedPars, aes(x = E_choice, y = vpp_A))
  # Scatter plot with regression line
  j + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}

  k <- ggplot(mergedPars, aes(x = E_choice, y = vpp_alpha))
  # Scatter plot with regression line
  k + geom_point()+
      geom_smooth(method = "lm") 

```

```{r}

  l <- ggplot(mergedPars, aes(x = E_choice, y = vpp_cons))
  # Scatter plot with regression line
  l + geom_point()+
      geom_smooth(method = "lm") 

```

```{r}

  m <- ggplot(mergedPars, aes(x = E_choice, y = vpp_lambda))
  # Scatter plot with regression line
  m + geom_point()+
      geom_smooth(method = "lm") 

```


```{r}

  n <- ggplot(mergedPars, aes(x = E_choice, y = vpp_epP))
  # Scatter plot with regression line
  n + geom_point()+
      geom_smooth(method = "lm") 

```

```{r}

  o <- ggplot(mergedPars, aes(x = E_choice, y = vpp_epN))
  # Scatter plot with regression line
  o + geom_point()+
      geom_smooth(method = "lm") 

```

```{r}

  p <- ggplot(mergedPars, aes(x = E_choice, y = vpp_K))
  # Scatter plot with regression line
  p + geom_point()+
      geom_smooth(method = "lm") 

```

```{r}

  q <- ggplot(mergedPars, aes(x = E_choice, y = vpp_w))
  # Scatter plot with regression line
  q + geom_point()+
      geom_smooth(method = "lm") 

```


correlation matrix

```{r}
corr<-cor(mergedPars)
ggcorrplot(corr)
corr
ggcorrplot(corr, hc.order = TRUE, type = "lower",
           lab = FALSE)
```

```{r}
corrpvl<-cor(pvlPars)
ggcorrplot(corrpvl)
ggcorrplot(corrpvl, hc.order = TRUE, type = "lower",
           lab = TRUE)
```

```{r}
corrorl<-cor(orlPars)
ggcorrplot(corrorl)
ggcorrplot(corrorl, hc.order = TRUE, type = "lower",
           lab = TRUE)
```

```{r}
corrvpp<-cor(vppPars)
ggcorrplot(corrvpp)
ggcorrplot(corrvpp, hc.order = TRUE, type = "lower",
           lab = TRUE)
```